[tool.poetry]
name = "connector"
version = "0.1.1"
description = "MYSQL query executor with pandas"
authors = ["yangroro <yang@heechan.kr>"]
license = "MIT"
packages = [
    { include = "connector" },
]
readme = "README.md"

repository = "https://github.com/alpha-trading/connector"
homepage = "https://github.com/alpha-trading/connector"

[tool.poetry.dependencies]
python = "^3.7"
pymysql = "^0.9.3"
python-dotenv = "^0.14.0"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
